version: '3.8'

services:
  # 1. SETUP
  setup:
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: ["/usr/local/bin/setup.sh"]
    volumes:
      - shared_data:/shared

  # 2. TESSERACT SERVER
  tesseract:
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: ["/usr/local/bin/tesseract-bin"]
    environment:
      - AWS_REGION=eu-west-1
    command: [
      "--http_endpoint=0.0.0.0:6962",
      "--roots_pem_file=/shared/combined_roots.pem",
      "--path_prefix=test-static-ct",
      "--origin=test-static-ct",
      "--bucket=${TESSERACT_BUCKET_NAME}",
      "--db_name=tesseract",
      "--db_host=${TESSERACT_DB_HOST}",
      "--db_port=3306",
      "--db_user=tesseract",
      "--db_password=${TESSERACT_DB_PASSWORD}",
      "--antispam_db_name=antispam_db",
      "--signer_public_key_secret_name=${TESSERACT_SIGNER_ECDSA_P256_PUBLIC_KEY_ID}",
      "--signer_private_key_secret_name=${TESSERACT_SIGNER_ECDSA_P256_PRIVATE_KEY_ID}",
      "--enable_publication_awaiter=false",
      "--rate_limit_dedup=-1",
      "--garbage_collection_interval=1m",
      "--v=1"
    ]
    volumes:
      - shared_data:/shared
    depends_on:
      setup:
        condition: service_completed_successfully

  # 3. PRELOADERS
  preloaders-live:
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: ["/usr/local/bin/run_preloaders.sh"]
    environment:
      - AWS_REGION=eu-west-1
      - TESSERA_BASE_NAME=${TESSERA_BASE_NAME}
    command: ["--continuous=true", "--num_workers=${NUM_WORKERS:-32}", "--batch_size=${BATCH_SIZE:-1000}", "--parallel_submit=${PARALLEL_SUBMIT:-16}", "--parallel_fetch=${PARALLEL_FETCH:-4}"]
    volumes:
      - shared_data:/shared
    depends_on:
      - tesseract

  preloaders-history:
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: ["/usr/local/bin/run_preloaders.sh"]
    environment:
      - AWS_REGION=eu-west-1
      - TESSERA_BASE_NAME=${TESSERA_BASE_NAME}
    command: ["--start_index=${START_INDEX:-0}", "--num_workers=${NUM_WORKERS:-32}", "--batch_size=${BATCH_SIZE:-1000}", "--parallel_submit=${PARALLEL_SUBMIT:-16}", "--parallel_fetch=${PARALLEL_FETCH:-4}", "--continuous=${CONTINUOUS:-false}"]
    volumes:
      - shared_data:/shared
    depends_on:
      - tesseract

  # 4. INDEXER
  indexer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: ["/usr/local/bin/indexer"]
    environment:
      - AWS_REGION=eu-west-1
    command: ["--bucket=${TESSERACT_BUCKET_NAME}"]
    depends_on:
      - tesseract

  # 5. API
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: ["/usr/local/bin/api"]
    environment:
      - AWS_REGION=eu-west-1
    command: ["--bucket=${TESSERACT_BUCKET_NAME}", "--log_origin=${TESSERA_BASE_NAME}"]
    ports:
      - "8080:8080"
    depends_on:
      - indexer

volumes:
  shared_data:
